### PR TITLE
Feat/video review card

### PR DESCRIPTION
**Pull request by Udit063**
Created the video card and set up the video recording
image

### CODE REVIEW

**Comment by Ankur1493** [comment]
working properly fine, add a video recording of platform

**Comment by Udit063** [comment]
https://github.com/user-attachments/assets/824aaef8-2463-454e-828c-345f0428c929

**Comment by Ankur1493** [comment]
works for now, but the animation is really bad, I wanted a smooth increase in width and the content showing up.. Learn how to do these animations and learn GSAP animations and other things from yt, and then do that

**Comment by Udit063** [comment]
yeah will learn it and implement it.

**Pull request merged**
