### PR TITLE
Review testimonials

### PR DESCRIPTION
**Pull request by Udit063**
Review testimonial Ui

### CODE REVIEW

**Comment by Ankur1493** [comment]
Add a proper description, with screenshots of all the UI changes you made, and the coding changes you made in frontend

**Comment by Udit063** [comment]
Added and updated the zustand states for customer details and text review with tags.
Updated UI in:
1. Customer Detail card -  Profile pic, Font size, heights and padding and some functionality.
2. Text Review card -  Stars, Tags, Characters and whole Page with appropriate spacing and size
3. Video Review Card -  Stars and ui for whole page
4. Thankyou card
5. Wrong URL Page

https://github.com/user-attachments/assets/6e63865c-de87-4b72-895e-a34ad4e7b51e

**Comment by Ankur1493** [comment]
Update star colors to golden, why blue?

**Comment by Ankur1493** [comment]
Everything else looks good, we'll have to work on the the thank you screen, /a url

**Comment by Udit063** [comment]
Stars are of blue color only in figma design, that's why i kept it as blue. If looking odd, then i can change to yellow.

**Pull request merged**
